# Generated by Django 6.0.4 on 2026-06-07 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("content", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("scratch", "Create from Scratch"),
                        ],
                        default="scratch",
                        max_length=20,
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("classic", "Classic"),
                            ("modern", "Modern"),
                            ("ats", "ATS Friendly"),
                        ],
                        default="classic",
                        max_length=50,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("resume", "Resume"), ("cv", "CV")],
                        default="resume",
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "storage_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("enhancement_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
